// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { PrismaLibSQL } from "@prisma/adapter-libsql";
import { createClient } from "@libsql/client";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts",
  },
  datasource: {
    adapter: () => {
      const client = createClient({
        url: process.env["TURSO_DATABASE_URL"]!,
        authToken: process.env["TURSO_AUTH_TOKEN"],
      });
      return new PrismaLibSQL(client);
    },
  },
});
