// ─── Implementation Quality Checks ───────────────────────────────────────────
// Evaluates whether each project's implementation plan is complete, specific,
// and readable by a federal grant reviewer.

import type { FilingSnapshot } from '@/actions/filings'
import type { ReviewFinding } from '../types'
import { slug, detectVagueTerms, mentionsContractor, mentionsTesting, isTooShort } from '../utils'

export function checkImplementation(snapshot: FilingSnapshot): ReviewFinding[] {
  const findings: ReviewFinding[] = []

  for (const project of snapshot.projects) {
    const pid = slug(project.id)
    const narrative = project.implementationNarrative ?? ''
    const source = project.implementationSource

    if (!narrative.trim()) continue // already flagged by completeness

    // ── Auto-generated narrative — recommend human review ─────────────────

    if (source === 'inferred') {
      findings.push({
        id: `implementation-auto-generated-${pid}`,
        severity: 'suggestion',
        category: 'implementation',
        title: 'Implementation Plan was auto-generated',
        explanation:
          `The implementation plan for "${project.title}" was generated by NSGP Builder based on the project type. Auto-generated plans use reasonable templates, but should be reviewed and tailored to your specific situation, vendors, and site conditions before submission.`,
        affectedSection: 'Investment Justification — Implementation Plan',
        affectedEntityId: project.id,
        affectedEntityLabel: project.title,
        recommendedAction:
          'Review the auto-generated implementation plan. Add specific vendor names, permit requirements, local code references, or site-specific installation details that make the plan concrete.',
        canAutoFix: false,
        resolved: false,
        rejected: false,
      })
    }

    // ── Vague language ────────────────────────────────────────────────────

    const vagueMatches = detectVagueTerms(narrative)
    if (vagueMatches.length > 0) {
      findings.push({
        id: `implementation-vague-language-${pid}`,
        severity: 'warning',
        category: 'implementation',
        title: 'Implementation Plan contains vague language',
        explanation:
          `The implementation plan for "${project.title}" contains phrases that weaken the narrative: ${vagueMatches.slice(0, 3).map((m) => `"${m}"`).join(', ')}. FEMA reviewers flag applications that use uncertain or non-committal language.`,
        affectedSection: 'Investment Justification — Implementation Plan',
        affectedEntityId: project.id,
        affectedEntityLabel: project.title,
        recommendedAction:
          'Replace vague phrases with specific commitments. Instead of "TBD", write the actual plan. Instead of "ASAP", write "within 30 days of award".',
        canAutoFix: true,
        proposedFix: {
          type: 'text_replacement',
          targetPath: `projects[${project.id}].implementationNarrative`,
          original: narrative,
          proposed:
            narrative
              .replace(/\bTBD\b/gi, '[specify timeframe or responsible party]')
              .replace(/\bto be determined\b/gi, '[specify]')
              .replace(/\bASAP\b/gi, 'within 30 days of award notification')
              .replace(/\bas soon as possible\b/gi, 'within 30 days of award notification')
              .replace(/\bvarious\b/gi, '[specify]')
              .replace(/\bif needed\b/gi, 'as required by the installation plan')
              .replace(/\bif necessary\b/gi, 'as required by the installation plan')
              .replace(/\bas needed\b/gi, 'per the installation schedule')
              .replace(/\bsoon\b/gi, 'within the first 60 days')
              .replace(/\bin the future\b/gi, 'within the period of performance'),
          requiresEvidenceConfirmation: false,
          guardrailTags: [],
        },
        resolved: false,
        rejected: false,
      })
    }

    // ── No contractor / implementer mentioned ─────────────────────────────

    if (!mentionsContractor(narrative)) {
      findings.push({
        id: `implementation-no-contractor-${pid}`,
        severity: 'suggestion',
        category: 'implementation',
        title: 'Implementation Plan does not name who will do the work',
        explanation:
          `The implementation plan for "${project.title}" does not clearly identify who will perform the installation: a licensed contractor, an in-house facilities team, or a security integrator. FEMA reviewers expect to see that qualified parties have been identified.`,
        affectedSection: 'Investment Justification — Implementation Plan',
        affectedEntityId: project.id,
        affectedEntityLabel: project.title,
        recommendedAction:
          'Specify who will do the work: a licensed contractor, certified security integrator, or in-house facilities staff. Include any relevant credentials or licensure. Evidence needed — user must confirm.',
        canAutoFix: false,
        resolved: false,
        rejected: false,
      })
    }

    // ── No testing or closeout mentioned ──────────────────────────────────

    if (!mentionsTesting(narrative)) {
      findings.push({
        id: `implementation-no-testing-${pid}`,
        severity: 'suggestion',
        category: 'implementation',
        title: 'Implementation Plan does not address testing or closeout',
        explanation:
          `The implementation plan for "${project.title}" does not mention how the completed installation will be tested or accepted. FEMA expects applicants to verify that funded equipment is operational before closeout.`,
        affectedSection: 'Investment Justification — Implementation Plan',
        affectedEntityId: project.id,
        affectedEntityLabel: project.title,
        recommendedAction:
          'Add a sentence describing how completion will be verified: system testing, walk-through inspection, or vendor sign-off.',
        canAutoFix: false,
        resolved: false,
        rejected: false,
      })
    }

    // ── Very short narrative ───────────────────────────────────────────────

    if (isTooShort(narrative, 120)) {
      findings.push({
        id: `implementation-too-short-${pid}`,
        severity: 'suggestion',
        category: 'implementation',
        title: 'Implementation Plan is very brief',
        explanation:
          `The implementation plan for "${project.title}" is short and may not give reviewers enough confidence that the implementation has been thought through.`,
        affectedSection: 'Investment Justification — Implementation Plan',
        affectedEntityId: project.id,
        affectedEntityLabel: project.title,
        recommendedAction:
          'Expand the implementation plan to include: who will do the work, key steps (procurement, site prep, installation, testing), permits required, and how completion will be verified.',
        canAutoFix: false,
        resolved: false,
        rejected: false,
      })
    }
  }

  return findings
}
