// ─── Sustainment Quality Checks ───────────────────────────────────────────────
// FEMA requires applicants to demonstrate they will maintain grant-funded
// equipment beyond the period of performance.

import type { FilingSnapshot } from '@/actions/filings'
import type { ReviewFinding } from '../types'
import { slug, detectVagueTerms, mentionsMaintenance, mentionsOwnership, isTooShort } from '../utils'

export function checkSustainment(snapshot: FilingSnapshot): ReviewFinding[] {
  const findings: ReviewFinding[] = []

  for (const project of snapshot.projects) {
    const pid = slug(project.id)
    const narrative = project.sustainmentNarrative ?? ''
    const source = project.sustainmentSource

    if (!narrative.trim()) continue // already flagged by completeness

    // ── Auto-generated narrative ──────────────────────────────────────────

    if (source === 'inferred') {
      findings.push({
        id: `sustainment-auto-generated-${pid}`,
        severity: 'suggestion',
        category: 'sustainment',
        title: 'Sustainment Plan was auto-generated',
        explanation:
          `The sustainment plan for "${project.title}" was auto-generated by NSGP Builder. While the template covers the basics, grant reviewers want to see organization-specific commitments: who is responsible, what budget covers maintenance, and what the service schedule looks like.`,
        affectedSection: 'Investment Justification — Sustainment Plan',
        affectedEntityId: project.id,
        affectedEntityLabel: project.title,
        recommendedAction:
          'Personalize the sustainment plan: name the staff role responsible for maintenance, describe the maintenance budget source, and reference any vendor warranty or service agreements.',
        canAutoFix: false,
        resolved: false,
        rejected: false,
      })
    }

    // ── Vague language ────────────────────────────────────────────────────

    const vagueMatches = detectVagueTerms(narrative)
    if (vagueMatches.length > 0) {
      findings.push({
        id: `sustainment-vague-language-${pid}`,
        severity: 'warning',
        category: 'sustainment',
        title: 'Sustainment Plan contains vague language',
        explanation:
          `The sustainment plan for "${project.title}" contains non-specific phrases that weaken the commitment: ${vagueMatches.slice(0, 3).map((m) => `"${m}"`).join(', ')}. Reviewers want definitive statements of responsibility and schedule.`,
        affectedSection: 'Investment Justification — Sustainment Plan',
        affectedEntityId: project.id,
        affectedEntityLabel: project.title,
        recommendedAction:
          'Replace vague language with specific maintenance commitments. Example: replace "as needed" with "quarterly" or "annually per manufacturer recommendation".',
        canAutoFix: true,
        proposedFix: {
          type: 'text_replacement',
          targetPath: `projects[${project.id}].sustainmentNarrative`,
          original: narrative,
          proposed:
            narrative
              .replace(/\bTBD\b/gi, '[specify]')
              .replace(/\bto be determined\b/gi, '[specify]')
              .replace(/\bASAP\b/gi, 'on an annual basis')
              .replace(/\bas soon as possible\b/gi, 'on a scheduled basis')
              .replace(/\bas needed\b/gi, 'on a regularly scheduled basis per manufacturer guidelines')
              .replace(/\bif needed\b/gi, 'as required by the maintenance schedule')
              .replace(/\bif necessary\b/gi, 'as required by the service agreement')
              .replace(/\bvarious\b/gi, '[specify responsible parties]')
              .replace(/\bsoon\b/gi, 'within the first year post-installation')
              .replace(/\bin the future\b/gi, 'within the organization\'s ongoing operational budget'),
          requiresEvidenceConfirmation: false,
          guardrailTags: [],
        },
        resolved: false,
        rejected: false,
      })
    }

    // ── No maintenance frequency mentioned ────────────────────────────────

    if (!mentionsMaintenance(narrative)) {
      findings.push({
        id: `sustainment-no-maintenance-frequency-${pid}`,
        severity: 'warning',
        category: 'sustainment',
        title: 'Sustainment Plan does not state maintenance frequency',
        explanation:
          `The sustainment plan for "${project.title}" does not mention how often maintenance will occur. FEMA expects applicants to commit to a specific schedule (annual, quarterly, per manufacturer specs, etc.).`,
        affectedSection: 'Investment Justification — Sustainment Plan',
        affectedEntityId: project.id,
        affectedEntityLabel: project.title,
        recommendedAction:
          'Add a maintenance frequency statement. Example: "Equipment will be inspected quarterly and serviced annually in accordance with manufacturer specifications."',
        canAutoFix: true,
        proposedFix: {
          type: 'text_replacement',
          targetPath: `projects[${project.id}].sustainmentNarrative`,
          original: narrative,
          proposed:
            narrative.trimEnd() +
            ' Equipment will be inspected on a regular basis and serviced per manufacturer recommendations, with annual preventive maintenance checks performed by facilities staff or a qualified service technician.',
          requiresEvidenceConfirmation: false,
          guardrailTags: [],
        },
        resolved: false,
        rejected: false,
      })
    }

    // ── No ownership / responsible party ─────────────────────────────────

    if (!mentionsOwnership(narrative)) {
      findings.push({
        id: `sustainment-no-ownership-${pid}`,
        severity: 'suggestion',
        category: 'sustainment',
        title: 'Sustainment Plan does not name who is responsible',
        explanation:
          `The sustainment plan for "${project.title}" does not identify who within the organization is responsible for maintaining the equipment. FEMA wants a named role or position — not just a general commitment.`,
        affectedSection: 'Investment Justification — Sustainment Plan',
        affectedEntityId: project.id,
        affectedEntityLabel: project.title,
        recommendedAction:
          'Name the staff role responsible for overseeing maintenance (e.g., Facilities Manager, Executive Director, Security Director).',
        canAutoFix: false,
        resolved: false,
        rejected: false,
      })
    }

    // ── Very short narrative ───────────────────────────────────────────────

    if (isTooShort(narrative, 100)) {
      findings.push({
        id: `sustainment-too-short-${pid}`,
        severity: 'suggestion',
        category: 'sustainment',
        title: 'Sustainment Plan is very brief',
        explanation:
          `The sustainment plan for "${project.title}" is short. A strong sustainment plan covers: who maintains it, how often, what budget funds it, and any warranty or service agreement.`,
        affectedSection: 'Investment Justification — Sustainment Plan',
        affectedEntityId: project.id,
        affectedEntityLabel: project.title,
        recommendedAction:
          'Expand the sustainment plan to address: responsible staff, maintenance frequency, funding source, and warranty/service coverage.',
        canAutoFix: false,
        resolved: false,
        rejected: false,
      })
    }
  }

  return findings
}
