import type { ValidationResult, ValidationIssue, DocumentStatus } from '@/lib/export-validation'
import { STATUS_LABELS, STATUS_COLORS } from '@/lib/export-validation'
import type { FilingSnapshot } from '@/actions/filings'
import { formatCurrency } from '@/lib/scoring'

// ─── SAA/FEMA attachments not generated by this tool ─────────────────────────

const SAA_ATTACHMENTS = [
  {
    name: 'IRS 501(c)(3) Determination Letter',
    required: true,
    note: 'Upload as PDF attachment to SAA portal',
  },
  {
    name: 'SAM.gov Active Registration / UEI',
    required: true,
    note: 'Must be active at time of submission; renew annually at sam.gov',
  },
  {
    name: 'Nonprofit Security Plan (or summary)',
    required: false,
    note: 'Strongly recommended; some SAAs require it',
  },
  {
    name: 'Law Enforcement Threat Assessment Letter',
    required: false,
    note: 'Required by most SAAs; contact local FBI field office or police dept.',
  },
  {
    name: 'Site Photos (exterior / interior)',
    required: false,
    note: 'Recommended to support vulnerability narrative',
  },
  {
    name: 'Board of Directors Authorization Resolution',
    required: false,
    note: 'Some SAAs require evidence that the board authorized the application',
  },
  {
    name: "Applicant's SF-LLL (Lobbying Disclosure)",
    required: true,
    note: 'Required if any federal funds were used for lobbying',
  },
  {
    name: 'Vendor Quotes / Price Documentation',
    required: false,
    note: 'Required for any item ≥ $10,000; strongly recommended for all budget items',
  },
]

// ─── Sub-components ───────────────────────────────────────────────────────────

function CheckRow({
  label,
  pass,
  detail,
}: {
  label: string
  pass: boolean
  detail?: string
}) {
  return (
    <div
      className={`flex items-start gap-3 px-3 py-2 rounded border ${
        pass ? 'border-green-200 bg-green-50' : 'border-amber-200 bg-amber-50'
      }`}
    >
      <span
        className={`flex-shrink-0 w-5 h-5 rounded-full flex items-center justify-center text-[11px] font-bold mt-0.5 ${
          pass ? 'bg-green-600 text-white' : 'bg-amber-500 text-white'
        }`}
      >
        {pass ? '✓' : '!'}
      </span>
      <div className="flex-1 min-w-0">
        <p className={`text-sm font-medium ${pass ? 'text-green-900' : 'text-amber-900'}`}>
          {label}
        </p>
        {detail && (
          <p className={`text-xs mt-0.5 ${pass ? 'text-green-700' : 'text-amber-700'}`}>
            {detail}
          </p>
        )}
      </div>
    </div>
  )
}

function IssueRow({ issue }: { issue: ValidationIssue }) {
  const colors =
    issue.severity === 'error'
      ? { row: 'border-red-200 bg-red-50', badge: 'bg-red-600 text-white', text: 'text-red-900', sub: 'text-red-700' }
      : issue.severity === 'warning'
        ? { row: 'border-amber-200 bg-amber-50', badge: 'bg-amber-500 text-white', text: 'text-amber-900', sub: 'text-amber-700' }
        : { row: 'border-blue-200 bg-blue-50', badge: 'bg-blue-500 text-white', text: 'text-blue-900', sub: 'text-blue-700' }

  const icon = issue.severity === 'error' ? '✕' : issue.severity === 'warning' ? '⚠' : 'i'

  return (
    <div className={`flex items-start gap-3 px-3 py-2 rounded border ${colors.row}`}>
      <span
        className={`flex-shrink-0 w-5 h-5 rounded-full flex items-center justify-center text-[11px] font-bold mt-0.5 ${colors.badge}`}
      >
        {icon}
      </span>
      <div className="flex-1 min-w-0">
        <p className={`text-xs font-semibold uppercase tracking-wide ${colors.sub}`}>
          {issue.field}
          {issue.context && ` — ${issue.context}`}
        </p>
        <p className={`text-sm ${colors.text}`}>{issue.message}</p>
      </div>
    </div>
  )
}

// ─── Main component ───────────────────────────────────────────────────────────

export function FormReadinessChecklist({
  snapshot,
  validation,
}: {
  snapshot: FilingSnapshot
  validation: ValidationResult
}) {
  const { issues, status, errorCount, warningCount } = validation
  const infoCount = issues.filter((i) => i.severity === 'info').length

  const errors = issues.filter((i) => i.severity === 'error')
  const warnings = issues.filter((i) => i.severity === 'warning')
  const infos = issues.filter((i) => i.severity === 'info')

  const statusColor = STATUS_COLORS[status]

  // Core form checks
  const hasThreats = snapshot.threats.length > 0
  const hasProjects = snapshot.projects.length > 0
  const hasBudgetItems = snapshot.projects.some((p) => p.budgetItems.length > 0)
  const hasNarratives = Object.keys(snapshot.narratives).length > 0

  // Budget math
  const computedTotal = snapshot.projects.reduce(
    (s, p) => s + p.budgetItems.reduce((b, i) => b + i.totalCost, 0),
    0,
  )
  const budgetMatch = Math.abs(computedTotal - snapshot.totalBudget) <= 0.01

  return (
    <div className="font-sans text-gray-900 bg-white" id="form-readiness-checklist">
      {/* ── Cover strip ── */}
      <div
        className="px-8 py-6 mb-6 border-b-4"
        style={{
          background: statusColor.bg,
          borderColor: statusColor.border,
        }}
      >
        <p className="text-xs uppercase tracking-widest font-semibold mb-1" style={{ color: statusColor.text }}>
          NSGP Builder — Submission Readiness Checklist
        </p>
        <h1 className="text-2xl font-bold mb-1" style={{ color: statusColor.text }}>
          {STATUS_LABELS[status as DocumentStatus]}
        </h1>
        <p className="text-sm" style={{ color: statusColor.text, opacity: 0.8 }}>
          {snapshot.organization.name} · {snapshot.site?.siteName ?? 'Unknown Site'} ·{' '}
          {formatCurrency(snapshot.totalBudget)} total request
        </p>
        <div className="mt-3 flex flex-wrap gap-4 text-xs font-semibold">
          {errorCount > 0 && (
            <span className="px-2 py-1 bg-red-600 text-white rounded">
              {errorCount} Error{errorCount !== 1 ? 's' : ''}
            </span>
          )}
          {warningCount > 0 && (
            <span className="px-2 py-1 bg-amber-500 text-white rounded">
              {warningCount} Warning{warningCount !== 1 ? 's' : ''}
            </span>
          )}
          {infoCount > 0 && (
            <span className="px-2 py-1 bg-blue-500 text-white rounded">
              {infoCount} Note{infoCount !== 1 ? 's' : ''}
            </span>
          )}
          {errorCount === 0 && warningCount === 0 && infoCount === 0 && (
            <span className="px-2 py-1 bg-green-600 text-white rounded">All checks passed</span>
          )}
        </div>
      </div>

      <div className="px-8 pb-8 space-y-8">
        {/* ── Section 1 — Core forms generated ── */}
        <section>
          <h2 className="text-sm font-bold uppercase tracking-wide text-slate-700 border-b-2 border-slate-800 pb-1 mb-3">
            1. Core Forms Generated
          </h2>
          <div className="space-y-2">
            <CheckRow label="SF-424 — Application for Federal Assistance" pass />
            <CheckRow label="Investment Justification (IJ) Narrative" pass />
            <CheckRow label="Budget Worksheet (SF-424A style)" pass />
            <CheckRow
              label="Threat Assessment Data"
              pass={hasThreats}
              detail={
                hasThreats
                  ? `${snapshot.threats.length} threat${snapshot.threats.length !== 1 ? 's' : ''} documented`
                  : 'No threat assessments entered — required for IJ narrative'
              }
            />
            <CheckRow
              label="Project Proposals"
              pass={hasProjects}
              detail={
                hasProjects
                  ? `${snapshot.projects.length} project${snapshot.projects.length !== 1 ? 's' : ''} · ${formatCurrency(snapshot.totalBudget)} total`
                  : 'No projects entered — required for budget and IJ sections'
              }
            />
            <CheckRow
              label="Budget Line Items"
              pass={hasBudgetItems}
              detail={hasBudgetItems ? undefined : 'No budget items on any project'}
            />
            <CheckRow
              label="Generated Narrative Sections"
              pass={hasNarratives}
              detail={
                hasNarratives
                  ? `${Object.keys(snapshot.narratives).length} sections`
                  : 'Run AI narrative generation before export'
              }
            />
            <CheckRow
              label="Budget Totals Balance"
              pass={budgetMatch}
              detail={
                budgetMatch
                  ? `${formatCurrency(computedTotal)} confirmed`
                  : `Line items sum to ${formatCurrency(computedTotal)} but snapshot shows ${formatCurrency(snapshot.totalBudget)} — regenerate draft`
              }
            />
          </div>
        </section>

        {/* ── Section 2 — Field Issues ── */}
        {(errors.length > 0 || warnings.length > 0) && (
          <section>
            <h2 className="text-sm font-bold uppercase tracking-wide text-slate-700 border-b-2 border-slate-800 pb-1 mb-3">
              2. Required Field Issues
            </h2>
            {errors.length > 0 && (
              <div className="mb-3">
                <p className="text-xs font-semibold text-red-700 uppercase tracking-wide mb-2">
                  Errors — must be fixed before submission
                </p>
                <div className="space-y-1.5">
                  {errors.map((issue, i) => (
                    <IssueRow key={i} issue={issue} />
                  ))}
                </div>
              </div>
            )}
            {warnings.length > 0 && (
              <div>
                <p className="text-xs font-semibold text-amber-700 uppercase tracking-wide mb-2">
                  Warnings — review before submission
                </p>
                <div className="space-y-1.5">
                  {warnings.map((issue, i) => (
                    <IssueRow key={i} issue={issue} />
                  ))}
                </div>
              </div>
            )}
          </section>
        )}

        {/* ── Section 3 — NOFO-dependent fields and auto-generation notices ── */}
        {infos.length > 0 && (
          <section>
            <h2 className="text-sm font-bold uppercase tracking-wide text-slate-700 border-b-2 border-slate-800 pb-1 mb-3">
              3. Notes &amp; Pending Items
            </h2>
            <p className="text-xs text-slate-500 mb-3">
              NOFO-dependent SF-424 fields (Congressional Districts, Proposed Dates) cannot be
              completed until FEMA publishes the Notice of Funding Opportunity. Auto-generated
              narrative notices are review prompts — confirm generated content before submission.
            </p>
            <div className="space-y-1.5">
              {infos.map((issue, i) => (
                <IssueRow key={i} issue={issue} />
              ))}
            </div>
          </section>
        )}

        {/* ── Section 4 — SAA attachments ── */}
        <section>
          <h2 className="text-sm font-bold uppercase tracking-wide text-slate-700 border-b-2 border-slate-800 pb-1 mb-3">
            4. SAA / FEMA Required Attachments
          </h2>
          <p className="text-xs text-slate-500 mb-3">
            The following documents are not generated by NSGP Builder. Attach them to your SAA
            portal submission package. Requirements vary by state — verify with your SAA.
          </p>
          <table className="w-full text-sm border-collapse">
            <thead>
              <tr className="bg-slate-100">
                <th className="border border-slate-300 p-2 text-left">Attachment</th>
                <th className="border border-slate-300 p-2 text-center w-24">Required</th>
                <th className="border border-slate-300 p-2 text-left">Notes</th>
              </tr>
            </thead>
            <tbody>
              {SAA_ATTACHMENTS.map((att, i) => (
                <tr key={i} className="even:bg-slate-50">
                  <td className="border border-slate-300 p-2 font-medium">{att.name}</td>
                  <td className="border border-slate-300 p-2 text-center">
                    <span
                      className={`text-xs font-semibold px-2 py-0.5 rounded ${
                        att.required
                          ? 'bg-red-100 text-red-700'
                          : 'bg-slate-200 text-slate-600'
                      }`}
                    >
                      {att.required ? 'Required' : 'Varies'}
                    </span>
                  </td>
                  <td className="border border-slate-300 p-2 text-xs text-slate-600">
                    {att.note}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        {/* ── Section 5 — Project completeness matrix ── */}
        <section>
          <h2 className="text-sm font-bold uppercase tracking-wide text-slate-700 border-b-2 border-slate-800 pb-1 mb-3">
            5. Project Section Completeness
          </h2>
          <table className="w-full text-sm border-collapse">
            <thead>
              <tr className="bg-slate-100">
                <th className="border border-slate-300 p-2 text-left">Section</th>
                {snapshot.projects.map((p, i) => (
                  <th key={p.id} className="border border-slate-300 p-2 text-center text-xs">
                    Project {i + 1}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {[
                { label: 'Problem Statement', key: 'problemStatement' as const },
                { label: 'Proposed Solution', key: 'proposedSolution' as const },
                { label: 'Risk Reduction Rationale', key: 'riskReductionRationale' as const },
                { label: 'Budget Items', key: '_budget' as const },
                { label: 'Threat Links', key: '_threats' as const },
              ].map((row) => (
                <tr key={row.label} className="even:bg-slate-50">
                  <td className="border border-slate-300 p-2 font-medium">{row.label}</td>
                  {snapshot.projects.map((p) => {
                    let hasValue: boolean
                    if (row.key === '_budget') {
                      hasValue = p.budgetItems.length > 0
                    } else if (row.key === '_threats') {
                      hasValue = p.linkedThreatTypes.length > 0
                    } else {
                      hasValue = !!(p[row.key] as string | null | undefined)?.trim()
                    }
                    return (
                      <td key={p.id} className="border border-slate-300 p-2 text-center">
                        <span
                          className={`text-xs font-bold ${
                            hasValue ? 'text-green-600' : 'text-amber-500'
                          }`}
                        >
                          {hasValue ? '✓' : '—'}
                        </span>
                      </td>
                    )
                  })}
                </tr>
              ))}
              {/* Implementation, Timeline, Sustainment — now generated or user-authored */}
              {[
                { label: 'Implementation Plan', sourceKey: 'implementationSource', narrativeKey: 'implementationNarrative' },
                { label: 'Estimated Timeline / Milestones', sourceKey: 'timelineSource', narrativeKey: 'timelineNarrative' },
                { label: 'Sustainment / Maintenance Plan', sourceKey: 'sustainmentSource', narrativeKey: 'sustainmentNarrative' },
              ].map(({ label, sourceKey, narrativeKey }) => (
                <tr key={label} className="even:bg-slate-50">
                  <td className="border border-slate-300 p-2 font-medium">
                    {label}
                  </td>
                  {snapshot.projects.map((p) => {
                    const proj = p as Record<string, unknown>
                    const hasNarrative = !!(proj[narrativeKey] as string | undefined)?.trim()
                    const source = proj[sourceKey] as string | undefined
                    const badge =
                      source === 'user' ? 'User' : source === 'structured' ? 'Generated' : 'Auto'
                    return (
                      <td key={p.id} className="border border-slate-300 p-2 text-center">
                        {hasNarrative ? (
                          <span className="text-xs font-bold text-green-600">
                            ✓
                            <span className="ml-0.5 text-[9px] font-normal text-slate-400">{badge}</span>
                          </span>
                        ) : (
                          <span className="text-xs font-bold text-amber-500">—</span>
                        )}
                      </td>
                    )
                  })}
                </tr>
              ))}
            </tbody>
          </table>
          <p className="text-xs text-slate-500 italic mt-2">
            Implementation Plan, Timeline, and Sustainment sections are auto-generated by NSGP
            Builder from project type and budget data when not user-authored. Review generated
            content before submission. &ldquo;User&rdquo; = user-authored; &ldquo;Generated&rdquo; =
            from structured inputs; &ldquo;Auto&rdquo; = inferred from project type.
          </p>
        </section>

        {/* ── Disclaimer ── */}
        <div className="rounded border border-slate-300 bg-slate-50 px-4 py-3">
          <p className="text-xs text-slate-600 leading-relaxed">
            <strong>Disclaimer:</strong> This checklist is generated by NSGP Builder and is intended
            as a planning aid only. It does not constitute legal or compliance advice. Requirements
            vary by state and are updated annually with each NOFO. Always verify requirements
            directly with your State Administrative Agency (SAA) and review the current FEMA NSGP
            Notice of Funding Opportunity before submitting.
          </p>
        </div>
      </div>
    </div>
  )
}
